### ISSUE TITLE
Snipcart webhook fails when "Shippable" lightswitch is toggled off

### ISSUE THREAD

**Issue by brettburwell** [workingconcept/snipcart-craft-plugin#13]
**Describe the bug**
We have a product in Craft that has the _Shippable_ lightswitch toggled off in the _Snipcart Product Details_ field. Customers are able to successfully purchase the product, but after checkout I'm receiving a "Webhook has failed for your Snipcart account" email from Snipcart. 

Searching through the logs brought up the following error:
```
[error][TypeError] TypeError: Return value of workingconcept\snipcart\models\ProductDetails::isShippable() must be of the type bool, null returned in /server/path/vendor/workingconcept/craft-snipcart/src/models/ProductDetails.php:361

/server/path/vendor/workingconcept/craft-snipcart/src/models/ProductDetails.php(203): workingconcept\snipcart\models\ProductDetails->isShippable(Object(workingconcept\snipcart\models\ProductDetails))
```

**To Reproduce**
1. Create a new product in Craft and fill out _Snipcart Product Details_ field, leaving the _Shippable_ lightswitch toggled off
2. Run through full checkout. 
3. Receive "Webhook failed" notification from Snipcart. 

**Expected behavior**
No warning email from Snipcart and product inventory successfully reduces. 

**Sofware**
 - Craft version: Pro 3.2.10
 - Snipcart plugin version: 1.1.3
 - PHP version: e.g. 7.3.12

**Additional context**
I don't believe it's related, but it feels worth mentioning that in _Snipcart Plugin Settings > Orders_ the _Reduce Item Quantities on Order?_ lightswitch is toggled on. There aren't any other relevant, interesting, or unusual settings (that I'm aware of!) on the Craft or Snipcart side of things, but if there's any additional info I can pass along let me know.

**Comment by mattstein** [comment]
Thanks for this, @brettburwell! I'll take a look and get back to you today.

**Comment by brettburwell** [comment]
Thanks for the quick reply duder!

**Comment by mattstein** [comment]
@brettburwell Just tagged a new release that should fix this. Would you mind updating to [1.2.4](https://github.com/workingconcept/snipcart-craft-plugin/releases/tag/1.2.4) and giving it a whirl?

Also, thanks for filing a beautiful issue that made it easy to track down. ❤

**Comment by brettburwell** [comment]
@mattstein Just updated and tested on staging and all looks well. Thank for such a quick fix!
