### ISSUE TITLE
Template Tags 'Cart Button' doesn't work with named arguments

### ISSUE THREAD

**Issue by handplant** [workingconcept/snipcart-craft-plugin#16]
When I use the following template tag as described in the documentation, I get an error in Twig.

**Tag**
`{{ craft.snipcart.cartLink(text='Shopping Cart', showCount=true) }}`

**Error**
`Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",").`

**Craft Version**
Craft Pro 3.4.27

**Snipcart Plugin Version**
1.3.4

**Twig version**
2.12.5

**Comment by mattstein** [comment]
Thanks for the issue, @handplant! 

You probably already know, but you can use that tag without named arguments and it will work as expected:

```twig
{{ craft.snipcart.cartLink("Shopping Cart", true) }}
```

I’ll get that fixed so named arguments are still an option.

**Comment by handplant** [comment]
Works! Thx

**Comment by mattstein** [comment]
Happy to help! I’m going to leave this open until I can fix the *named* argument functionality as documented.

**Comment by mattstein** [comment]
It turns out that’s not possible without changing the API, so I’ve fixed the docs instead. Sorry for the confusion!
