### ISSUE TITLE
Price field issue in german control panel

### ISSUE THREAD

**Issue by handplant** [workingconcept/snipcart-craft-plugin#17]
If I set my account to German, I can no longer maintain the price field.
For example, if I enter 55.50, the field converts the price to 5,550.00 after saving.

Snipcart Plugin 1.3.4

**Comment by mattstein** [comment]
I think I’ve got this solved in the `1.4.0` branch. Can you let me know if this solves the problem for you, @handplant?

Should be able to switch changing composer.json to...

```json
"workingconcept/craft-snipcart": "1.4.0.x-dev as 1.4.0",
```

...and running `composer update`.

**Comment by handplant** [comment]
Yes, thank you. Now the price field behaves correctly. Also in German language.

When will 1.4 be officially released?

**Comment by mattstein** [comment]
Great to hear! Just need to wrap up some testing and I should be able to release it later this week.
