### ISSUE TITLE
SKU error when trying to update inventory value on existing product

### ISSUE THREAD

**Issue by zizther** [workingconcept/snipcart-craft-plugin#21]
**Describe the bug**

I have products already setup. These all have unique and inventory values.
I have it that the Snipcart webhook updates the inventory value.
When updating the inventory values up or down it says the entry could not be saved because `SKU must be unique.`

The SKUs are all unique, so it seems that some in Craft 3.5 has changed, as it was all working in 3.4.
It looks like it is checking the entry against itself before saving, which is why it is showing the error, as the SKU already exists for itself.

**To Reproduce**

1. Enable the webhook for snipcart to reduce the inventory value
2. Create an entry with a unique SKU and inventory value.
3. Edit the entry inventory value
4. Save the entry
5. See error

**Expected behavior**

When updating a products inventory value the entry should save with the updated value

**Screenshots**
<img width="911" alt="" src="https://user-images.githubusercontent.com/1436378/92132795-827e9a80-edff-11ea-89ea-a4fc8ae6521e.png">

**Software**

 - Craft version: Pro 3.5.8
 - Snipcart plugin version: 1.4.2
 - PHP version: 7.2
 - Browser: Chrome

**Comment by mattstein** [comment]
Thanks for reporting this @zizther! I’m not sure how I missed this testing with 3.5 but I’ll get it resolved as soon as I can.

**Comment by mattstein** [comment]
Would you mind switching to `workingconcept/craft-snipcart` to `dev-develop` and confirming that fixes the issue @zizther? Just finished testing locally and that should do the trick.

**Comment by zizther** [comment]
Solid turn around. Good work.
I have tested and my issues are resolved.

Thanks for sorting this so quickly

**Comment by mattstein** [comment]
Just released [1.4.3](https://github.com/workingconcept/snipcart-craft-plugin/releases/tag/1.4.3) with this fix.
