### ISSUE TITLE
Process new snipcart webhooks

### ISSUE THREAD

**Issue by tobystokes** [workingconcept/snipcart-craft-plugin#23]
**Describe the bug**

Since https://docs.snipcart.com/v3/release-notes#aug-19-2020

[A webhook is now sent when issuing order refunds.](https://docs.snipcart.com/v3/webhooks/order-events#orderrefundcreated)
[A webhook is now sent when a notification is added to an order.](https://docs.snipcart.com/v3/webhooks/order-events#ordernotificationcreated)

**To Reproduce**

```
{
  "eventName": "order.notification.created",
  "mode": "Live",
  "createdOn": "2020-09-17T21:09:29.0873579Z",
  "content": {
    "orderToken": "XXX",
    "notificationType": "OrderStatusChanged",
    "sentByEmail": false,
    "sentByEmailOn": null,
    "subject": null,
    "body": null,
    "message": "Order status changed from 'Processed' to 'Shipped'."
  }
}
```
**Expected behavior**

200 response instead of 400

**Software**

 - Snipcart plugin version: 1.4.3.1

**Additional context**

Not a breaking issue, and I have no need to process these webhooks, but Snipcart is sending regular 'A webhook has failed' emails.

**Comment by mattstein** [comment]
Thanks for the issue, @tobystokes! I’ll get both of those added.

**Comment by mattstein** [comment]
Just added support for these in https://github.com/workingconcept/snipcart-craft-plugin/releases/tag/1.4.4.
